apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: stashcache
  name: stashcache
  namespace: osg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: stashcache
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: gpn-fiona-r740xd-node809.greatplains.net
      initContainers:
      - name: chowndata
        image: busybox
        command: ["sh", "-c", "chown -R 999:997 /data1"]
        volumeMounts:
        - name: datavol
          mountPath: /data1/stash
      containers:
      - name: stashcache
        image: efajardo/prp-stashcache
        imagePullPolicy: Always
        volumeMounts:
        - name: certs
          mountPath: /etc/grid-security/xrd
          readOnly: true
        - name: config
          mountPath: /etc/xrootd
        - name: datavol
          mountPath: /data1/stash
      volumes:
      - name: certs
        secret:
          secretName: certs
      - name: config
        configMap:
          name: stashcache
      - name: datavol
        hostPath:
          path: /data1
          type: Directory
